INSERT INTO `operatordb`.`planType` (`plan`) VALUES ('pre-paid');
INSERT INTO `operatordb`.`planType` (`plan`) VALUES ('post-paid');
INSERT INTO `operatordb`.`planType` (`plan`) VALUES ('generalPass');
INSERT INTO `operatordb`.`planType` (`plan`) VALUES ('passT0');
INSERT INTO `operatordb`.`planType` (`plan`) VALUES ('passT1');
INSERT INTO `operatordb`.`planType` (`plan`) VALUES ('passT2');
INSERT INTO `operatordb`.`planType` (`plan`) VALUES ('combined_T0_T1');
INSERT INTO `operatordb`.`planType` (`plan`) VALUES ('combined_T0_T2');
INSERT INTO `operatordb`.`planType` (`plan`) VALUES ('combined_T1_T2');
